#!/usr/bin/env bash
echo Welcome!
read -p "Print username: " user
read -p "Print groupname: " group

groupadd $group
cp /etc/sudoers{,.bkp}
echo '%' $group 'ALL=(ALL) ALL' >> /etc/sudoers
mkdir /home/$group
useradd $user -g $group -b /home/$group -s /bin/bash
